<<<<<<< HEAD
postgres:
  image: eeacms/postgres
  labels:
    io.rancher.sidekicks: data
  ports:
  - "5432:5432"
  volumes_from:
  - data
  volumes:
  - /etc/localtime:/etc/localtime:ro
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DBNAME: datafs zasync
    POSTGRES_DBUSER: zope
    POSTGRES_DBPASS: zope
=======
version: "3"
>>>>>>> c636968 (fix(default.conf): and apply more RelStorage tunning - refs #148213)

services:
  postgres:
    image: eeacms/postgres:11s
    ports:
    - "5432:5432"
    environment:
      POSTGRES_CONFIG: max_connections = 150
      POSTGRES_CRONS: ""
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: zope
      POSTGRES_DBUSER: zope
      POSTGRES_DBPASS: zope
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - postgres_dump:/postgresql.backup
    - postgres_archive:/var/lib/postgresql/archive

volumes:
  postgres_data: {}
  postgres_dump: {}
  postgres_archive: {}
