FROM busybox
MAINTAINER "Alin Voinea" <alin.voinea@eaudeweb.ro>

RUN mkdir -p /var/lib/postgresql/data
RUN mkdir -p /postgresql.conf.d
RUN mkdir -p /postgresql.backup
VOLUME /var/lib/postgresql/data
VOLUME /postgresql.conf.d
VOLUME /postgresql.backup
